#!/bin/bash
cp implementation/system.bit ../bit_files/c09f12_01_2014_Aug_08_1735.bit
./mkbof_64 -o implementation/system.bof -s core_info.tab -t 3 implementation/system.bin
chmod +x implementation/system.bof
cp implementation/system.bof ../bit_files/c09f12_01_2014_Aug_08_1735.bof
